project_id = "uvmkkyvysyvdcalfhziy"

[functions.generate-game]
verify_jwt = true

[functions.generate-thumbnail]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.generate-interface-image]
verify_jwt = true

[functions.analyze-interface]
verify_jwt = true