name: Supabase Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          set -e
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "amd64" ]; then
            FILE="supabase_linux_amd64.tar.gz"
          elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
            FILE="supabase_linux_arm64.tar.gz"
          else
            echo "Unsupported architecture: $ARCH" >&2
            exit 1
          fi
          URL="https://github.com/supabase/cli/releases/latest/download/${FILE}"
          echo "Downloading Supabase CLI from $URL"
          curl -L "$URL" -o /tmp/supabase.tar.gz
          tar -xzf /tmp/supabase.tar.gz -C /tmp
          sudo mv /tmp/supabase /usr/local/bin/supabase
          sudo chmod +x /usr/local/bin/supabase
          supabase --version

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Run migrations and deploy
        run: |
          supabase db push
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
